# Site Metadata
baseURL = "https://erinsaudiocorner.com/"
languageCode = "en-us"
title = "Erin's Audio Corner"
theme = "meghna-hugo"
uglyURLs = false
summaryLength = "15"

[pagination]
pageSize = 10


# Language Settings
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[languages.en]
languageName = "English"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"

# Markup
[markup.goldmark.renderer]
unsafe = true

# Params
[params]
logo = "https://dl.dropboxusercontent.com/s/7l7gj78pzfv5ufv/watermark%20-%20for%20site.png?dl=0"
description = "The Sound of Science"
author = "E"
google_analitycs_id = "UA-156925516-1"
post_share = true

[params.preloader]
enable = false
preloader = "images/logos/speaker_trans_tshirt.png"

# Map (optional)
[params.map]
enable = false
gmap_api = "YOUR_GOOGLE_MAP_API_KEY"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

# Social Links
[[params.social]]
icon = "ti-facebook"
link = "https://www.facebook.com/groups/607627396679113/?ref=group_header"

[[params.social]]
icon = "ti-youtube"
link = "https://www.youtube.com/user/hardisj/featured"

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"

[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

[[params.plugins.css]]
link = "plugins/animate-css/animate.css"

[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"

[[params.plugins.css]]
link = "plugins/slick/slick.css"

[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"

[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"

[[params.plugins.js]]
link = "plugins/slick/slick.min.js"

[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"

[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"

[[params.plugins.js]]
link = "plugins/wow/wow.min.js"

[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"

[[params.plugins.js]]
link = "plugins/google-map/map.js"

# Navigation Menu
[[menu.main]]
name = "Drive Units"
URL = "driveunits"
weight = 1

[[menu.main]]
name = "Loudspeakers"
URL = "loudspeakers"
weight = 2

[[menu.main]]
name = "Subwoofers"
URL = "subwoofer_testing"
weight = 3

[[menu.main]]
name = "Electronics"
URL = "electronics"
weight = 4

[[menu.main]]
name = "Leaderboard"
URL = "leaderboard"
weight = 5

[[menu.main]]
name = "Contribute"
URL = "contribute"
weight = 6
