################################# Default configuration ###################
baseURL = "https://erinsaudiocorner.com/"
languageCode = "en-us"
title = "Erin's Audio Corner"
theme = "meghna-hugo"
# post pagination
paginate = "1000"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []
[markup.goldmark.renderer]
unsafe= true

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/animate-css/animate.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/wow/wow.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"

############################# Navigation ##################################
[[menu.main]]
name = "Drive Units"
URL = "driveunits"
weight = 1

[[menu.main]]
name = "Loudspeakers"
URL = "loudspeakers"
weight = 2

[[menu.main]]
name = "Electronics"
URL = "electronics"
weight = 3

[[menu.main]]
name = "Test Methods"
URL = "testmethods"
weight = 4

[[menu.main]]
name = "About Me"
URL = "about"
weight = 5

#[[menu.main]]
#name = "Contact"
#URL = "contact"
#weight = 6

[[menu.main]]
name = "Time Delay"
URL = "timedelaycalc"
weight = 6


[[menu.main]]
name = "Contribute"
URL = "contribute"
weight = 7

############################# Default Parameters ##########################
[params]
logo = "images/logos/speaker_trans_small.png"  # banner logo (at top/bottom)
# Meta data
description = "The Sound of Science"
author = "E"
# Google Analitycs
google_analitycs_id = "UA-156925516-1" # Your ID
# post share
post_share = true
# themecss
## customCSS = [ "custom.css" ]

# preloader
[params.preloader]
enable = true
preloader = "images/logos/speaker_trans_tshirt.png" # pre-loader logo

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

############################# social icons ##########################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "https://www.facebook.com/groups/607627396679113/?ref=group_header"

[[params.social]]
icon = "ti-youtube" # themify icon pack : https://themify.me/themify-icons
link = "https://www.youtube.com/user/hardisj/featured"

################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
